name: Freeze python scripts to binaries

on:
  push:
    branches:
      - main
    paths:
      - 'payload/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Freeze python scripts to binaries
        run: |
          mkdir -p bin
          foreach ($script in Get-ChildItem -Path PyScripts -Filter *.py) {
            pyinstaller --onefile --distpath bin $script.FullName
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: payload-bin
          path: bin/*
