name: Convert Python scripts to binaries (Windows)

on:
  push:
    branches:
      - main
    paths:
      - 'PyScripts/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Convert Python scripts to binaries
        run: |
          mkdir -p bin
          foreach ($script in Get-ChildItem -Path PyScripts -Filter *.py) {
            pyinstaller --onefile --distpath bin $script.FullName
          }

      - name: Commit and push binaries
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/
          git commit -m "Auto-generated Windows binaries from PyScripts"
          git push