name: Convert Python to EXE on Windows

on:
  push:
    paths:
      - 'payload/**'
  workflow_dispatch:

jobs:
  convert-to-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Convert .py to .exe
      run: |
        if (-Not (Test-Path -Path bin)) {
          New-Item -ItemType Directory -Path bin
        }
        Get-ChildItem -Path payload\*.py | ForEach-Object {
          pyinstaller --onefile --distpath bin $_.FullName
        }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bin
        path: bin/

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add bin/
        git commit -m "Automated commit: Add compiled .exe files"
        git push
