name: Convert Python to EXE on Windows

on:
  push:
    paths:
      - 'payload/**'
  workflow_dispatch:

jobs:
  convert-to-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Convert .py to .exe
      run: |
        if not exist scripts mkdir scripts
        for %%f in (payload\*.py) do (
          pyinstaller --onefile --distpath scripts "%%f"
        )

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: scripts
        path: scripts/
