name: Freeze python scripts to binaries

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'payload/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Freeze python scripts to binaries
        run: |
          if (-Not (Test-Path -Path bin)) {
            New-Item -ItemType Directory -Path bin
          } else {
            Remove-Item -Path "bin" -Recurse -Force
            New-Item -ItemType Directory -Path bin
          }
          foreach ($script in Get-ChildItem -Path payload\*.py) {
            pyinstaller --onefile --distpath bin $script.FullName
          }

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin binaries
          git switch binaries
          git add bin/
          git commit -m "Automated commit: Update frozen binaries"
          git push
